;; Ziku Runtime Support
;; Generated by Ziku Scheme Backend

;; Pretty print result (matching IR eval output format)
(define (ziku-print-result v)
  (cond
    ((boolean? v) (display (if v "true" "false")))
    ((null? v) (display "()"))
    ((string? v)
     ;; Strings: output with double quotes like IR eval
     (display "\"")
     (display v)
     (display "\""))
    ((char? v)
     ;; Characters: output with single quotes like IR eval
     (display "'")
     (display v)
     (display "'"))
    ((pair? v)
     (if (and (pair? (car v)) (symbol? (caar v)))
         ;; Record
         (begin
           (display "{ ")
           (let loop ((fields v))
             (unless (null? fields)
               (display (caar fields))
               (display " = ")
               (ziku-print-result (cdar fields))
               (unless (null? (cdr fields))
                 (display ", "))
               (loop (cdr fields))))
           (display " }"))
         ;; Regular pair/list
         (begin
           (display "(")
           (ziku-print-result (car v))
           (display " . ")
           (ziku-print-result (cdr v))
           (display ")"))))
    ((procedure? v) (display "<function>"))
    (else (display v)))
  (newline))

;; Logical operators as functions (Scheme's and/or are special forms, not procedures)
(define (ziku-and a b) (and a b))
(define (ziku-or a b) (or a b))

;; Not-equal operator (works for all types)
(define (ziku-ne a b) (not (equal? a b)))

;; Main program
(define (ziku-main halt)
  (let ((_alpha0 halt)) (let ((_alpha1 (lambda (%fn0) (let ((%arg 3)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn0 %v) _alpha0))) ((%fn0 %arg) _alpha0)))))) (let ((_alpha2 (lambda (%fn1) (let ((%arg 2)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn1 %v) _alpha1))) ((%fn1 %arg) _alpha1)))))) (let ((%p (lambda (x) (lambda (_alpha3) (let ((%p (lambda (y) (lambda (_alpha4) (let ((%p (lambda (z) (lambda (_alpha5) (let ((_alpha6 _alpha5)) (let ((_alpha7 (lambda (_f0) (_alpha6 (+ _f0 z))))) (_alpha7 (+ x y)))))))) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha4) (_alpha4 %p))))))) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha3) (_alpha3 %p))))))) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%fn2) (let ((%arg 1)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn2 %v) _alpha2))) ((%fn2 %arg) _alpha2))))) ((lambda (%fn2) (let ((%arg 1)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn2 %v) _alpha2))) ((%fn2 %arg) _alpha2)))) %p)))))))

;; Run with result printer
(ziku-main ziku-print-result)
