;; Ziku Runtime Support
;; Generated by Ziku Scheme Backend

;; Pretty print result (matching IR eval output format)
(define (ziku-print-result v)
  (cond
    ((boolean? v) (display (if v "true" "false")))
    ((null? v) (display "()"))
    ((string? v)
     ;; Strings: output with double quotes like IR eval
     (display "\"")
     (display v)
     (display "\""))
    ((char? v)
     ;; Characters: output with single quotes like IR eval
     (display "'")
     (display v)
     (display "'"))
    ((pair? v)
     (if (and (pair? (car v)) (symbol? (caar v)))
         ;; Record
         (begin
           (display "{ ")
           (let loop ((fields v))
             (unless (null? fields)
               (display (caar fields))
               (display " = ")
               (ziku-print-result (cdar fields))
               (unless (null? (cdr fields))
                 (display ", "))
               (loop (cdr fields))))
           (display " }"))
         ;; Regular pair/list
         (begin
           (display "(")
           (ziku-print-result (car v))
           (display " . ")
           (ziku-print-result (cdr v))
           (display ")"))))
    ((procedure? v) (display "<function>"))
    (else (display v)))
  (newline))

;; Logical operators as functions (Scheme's and/or are special forms, not procedures)
(define (ziku-and a b) (and a b))
(define (ziku-or a b) (or a b))

;; Not-equal operator (works for all types)
(define (ziku-ne a b) (not (equal? a b)))

;; Main program
(define (ziku-main halt)
  (let ((_alpha0 halt)) (let ((f (letrec ((f (lambda (n) (lambda (_alpha1) (let ((_alpha2 _alpha1)) (let ((_alpha3 (lambda (_f0) (if _f0 (let ((%p 1)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha2) (_alpha2 %p))) (let ((_alpha4 _alpha2)) (let ((_alpha5 (lambda (_f1) (_alpha4 (* n _f1))))) (let ((_f2 f)) (let ((_alpha6 (lambda (_f3) (let ((%p _f2)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%fn0) (let ((%arg _f3)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn0 %v) _alpha5))) ((%fn0 %arg) _alpha5))))) ((lambda (%fn0) (let ((%arg _f3)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn0 %v) _alpha5))) ((%fn0 %arg) _alpha5)))) %p)))))) (_alpha6 (- n 1)))))))))) (_alpha3 (equal? n 0)))))))) f))) (let ((_alpha7 _alpha0)) (let ((%p f)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%fn1) (let ((%arg 5)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn1 %v) _alpha7))) ((%fn1 %arg) _alpha7))))) ((lambda (%fn1) (let ((%arg 5)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn1 %v) _alpha7))) ((%fn1 %arg) _alpha7)))) %p)))))))

;; Run with result printer
(ziku-main ziku-print-result)
