;; Ziku Runtime Support
;; Generated by Ziku Scheme Backend

;; Pretty print result (matching IR eval output format)
(define (ziku-print-result v)
  (cond
    ((boolean? v) (display (if v "true" "false")))
    ((null? v) (display "()"))
    ((string? v)
     ;; Strings: output with double quotes like IR eval
     (display "\"")
     (display v)
     (display "\""))
    ((char? v)
     ;; Characters: output with single quotes like IR eval
     (display "'")
     (display v)
     (display "'"))
    ((pair? v)
     (if (and (pair? (car v)) (symbol? (caar v)))
         ;; Record
         (begin
           (display "{ ")
           (let loop ((fields v))
             (unless (null? fields)
               (display (caar fields))
               (display " = ")
               (ziku-print-result (cdar fields))
               (unless (null? (cdr fields))
                 (display ", "))
               (loop (cdr fields))))
           (display " }"))
         ;; Regular pair/list
         (begin
           (display "(")
           (ziku-print-result (car v))
           (display " . ")
           (ziku-print-result (cdr v))
           (display ")"))))
    ((procedure? v) (display "<function>"))
    (else (display v)))
  (newline))

;; Logical operators as functions (Scheme's and/or are special forms, not procedures)
(define (ziku-and a b) (and a b))
(define (ziku-or a b) (or a b))

;; Not-equal operator (works for all types)
(define (ziku-ne a b) (not (equal? a b)))

;; Main program
(define (ziku-main halt)
  (let ((_alpha0 halt)) (let ((getX (lambda (r) (lambda (_alpha1) (let ((_alpha2 _alpha1)) (let ((%p r)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%rec) (let* ((%is-dispatch (and (vector? %rec) (eq? (vector-ref %rec 0) 'ziku-dispatch))) (%v (cond (%is-dispatch ((vector-ref %rec 1) 'x)) ((procedure? %rec) (%rec 'x)) (else (cdr (assq 'x %rec)))))) (if (and (vector? %v) (eq? (vector-ref %v 0) 'ziku-thunk)) ((vector-ref %v 1) _alpha2) (_alpha2 %v))))) ((lambda (%rec) (let* ((%is-dispatch (and (vector? %rec) (eq? (vector-ref %rec 0) 'ziku-dispatch))) (%v (cond (%is-dispatch ((vector-ref %rec 1) 'x)) ((procedure? %rec) (%rec 'x)) (else (cdr (assq 'x %rec)))))) (if (and (vector? %v) (eq? (vector-ref %v 0) 'ziku-thunk)) ((vector-ref %v 1) _alpha2) (_alpha2 %v)))) %p)))))))) (let ((_alpha3 _alpha0)) (let ((point (list (cons 'y 100) (cons 'x 42)))) (let ((_alpha4 _alpha3)) (let ((%p getX)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%fn0) (let ((%arg point)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn0 %v) _alpha4))) ((%fn0 %arg) _alpha4))))) ((lambda (%fn0) (let ((%arg point)) (if (and (vector? %arg) (eq? (vector-ref %arg 0) 'ziku-thunk)) ((vector-ref %arg 1) (lambda (%v) ((%fn0 %v) _alpha4))) ((%fn0 %arg) _alpha4)))) %p)))))))))

;; Run with result printer
(ziku-main ziku-print-result)
