;; Ziku Runtime Support
;; Generated by Ziku Scheme Backend

;; Pretty print result (matching IR eval output format)
(define (ziku-print-result v)
  (cond
    ((boolean? v) (display (if v "true" "false")))
    ((null? v) (display "()"))
    ((string? v)
     ;; Strings: output with double quotes like IR eval
     (display "\"")
     (display v)
     (display "\""))
    ((char? v)
     ;; Characters: output with single quotes like IR eval
     (display "'")
     (display v)
     (display "'"))
    ((pair? v)
     (if (and (pair? (car v)) (symbol? (caar v)))
         ;; Record
         (begin
           (display "{ ")
           (let loop ((fields v))
             (unless (null? fields)
               (display (caar fields))
               (display " = ")
               (ziku-print-result (cdar fields))
               (unless (null? (cdr fields))
                 (display ", "))
               (loop (cdr fields))))
           (display " }"))
         ;; Regular pair/list
         (begin
           (display "(")
           (ziku-print-result (car v))
           (display " . ")
           (ziku-print-result (cdr v))
           (display ")"))))
    ((procedure? v) (display "<function>"))
    (else (display v)))
  (newline))

;; Logical operators as functions (Scheme's and/or are special forms, not procedures)
(define (ziku-and a b) (and a b))
(define (ziku-or a b) (or a b))

;; Not-equal operator (works for all types)
(define (ziku-ne a b) (not (equal? a b)))

;; Main program
(define (ziku-main halt)
  (let ((_alpha0 halt)) (let ((c1 #\a)) (let ((_alpha1 _alpha0)) (let ((c2 #\a)) (let ((_alpha2 _alpha1)) (let ((c3 #\b)) (let ((_alpha3 _alpha2)) (let ((_alpha4 (lambda (_f0) (if _f0 (let ((_alpha5 _alpha3)) (let ((_alpha6 (lambda (_f1) (if _f1 (let ((%p 0)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha5) (_alpha5 %p))) (let ((_alpha7 _alpha5)) (let ((_alpha8 (lambda (_f2) (if _f2 (let ((%p 1)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha7) (_alpha7 %p))) (let ((%p 2)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha7) (_alpha7 %p))))))) (_alpha8 (ziku-ne c1 c3)))))))) (_alpha6 (equal? c2 c3)))) (let ((%p 3)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha3) (_alpha3 %p))))))) (_alpha4 (equal? c1 c2)))))))))))

;; Run with result printer
(ziku-main ziku-print-result)
