;; Ziku Runtime Support
;; Generated by Ziku Scheme Backend

;; Pretty print result (matching IR eval output format)
(define (ziku-print-result v)
  (cond
    ((boolean? v) (display (if v "true" "false")))
    ((null? v) (display "()"))
    ((string? v)
     ;; Strings: output with double quotes like IR eval
     (display "\"")
     (display v)
     (display "\""))
    ((char? v)
     ;; Characters: output with single quotes like IR eval
     (display "'")
     (display v)
     (display "'"))
    ((pair? v)
     (if (and (pair? (car v)) (symbol? (caar v)))
         ;; Record
         (begin
           (display "{ ")
           (let loop ((fields v))
             (unless (null? fields)
               (display (caar fields))
               (display " = ")
               (ziku-print-result (cdar fields))
               (unless (null? (cdr fields))
                 (display ", "))
               (loop (cdr fields))))
           (display " }"))
         ;; Regular pair/list
         (begin
           (display "(")
           (ziku-print-result (car v))
           (display " . ")
           (ziku-print-result (cdr v))
           (display ")"))))
    ((procedure? v) (display "<function>"))
    (else (display v)))
  (newline))

;; Logical operators as functions (Scheme's and/or are special forms, not procedures)
(define (ziku-and a b) (and a b))
(define (ziku-or a b) (or a b))

;; Not-equal operator (works for all types)
(define (ziku-ne a b) (not (equal? a b)))

;; Main program
(define (ziku-main halt)
  (let ((_alpha0 halt)) (let ((ones (letrec ((ones (vector 'ziku-dispatch (lambda (%field) (case %field ((tail) ones) ((head) 1)))))) ones))) (let ((_alpha1 _alpha0)) (let ((%p ones)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%rec) (let* ((%is-dispatch (and (vector? %rec) (eq? (vector-ref %rec 0) 'ziku-dispatch))) (%v (cond (%is-dispatch ((vector-ref %rec 1) 'head)) ((procedure? %rec) (%rec 'head)) (else (cdr (assq 'head %rec)))))) (if (and (vector? %v) (eq? (vector-ref %v 0) 'ziku-thunk)) ((vector-ref %v 1) _alpha1) (_alpha1 %v))))) ((lambda (%rec) (let* ((%is-dispatch (and (vector? %rec) (eq? (vector-ref %rec 0) 'ziku-dispatch))) (%v (cond (%is-dispatch ((vector-ref %rec 1) 'head)) ((procedure? %rec) (%rec 'head)) (else (cdr (assq 'head %rec)))))) (if (and (vector? %v) (eq? (vector-ref %v 0) 'ziku-thunk)) ((vector-ref %v 1) _alpha1) (_alpha1 %v)))) %p)))))))

;; Run with result printer
(ziku-main ziku-print-result)
