;; Ziku Runtime Support
;; Generated by Ziku Scheme Backend

;; Pretty print result (matching IR eval output format)
(define (ziku-print-result v)
  (cond
    ((boolean? v) (display (if v "true" "false")))
    ((null? v) (display "()"))
    ((string? v)
     ;; Strings: output with double quotes like IR eval
     (display "\"")
     (display v)
     (display "\""))
    ((char? v)
     ;; Characters: output with single quotes like IR eval
     (display "'")
     (display v)
     (display "'"))
    ((pair? v)
     (if (and (pair? (car v)) (symbol? (caar v)))
         ;; Record
         (begin
           (display "{ ")
           (let loop ((fields v))
             (unless (null? fields)
               (display (caar fields))
               (display " = ")
               (ziku-print-result (cdar fields))
               (unless (null? (cdr fields))
                 (display ", "))
               (loop (cdr fields))))
           (display " }"))
         ;; Regular pair/list
         (begin
           (display "(")
           (ziku-print-result (car v))
           (display " . ")
           (ziku-print-result (cdr v))
           (display ")"))))
    ((procedure? v) (display "<function>"))
    (else (display v)))
  (newline))

;; Logical operators as functions (Scheme's and/or are special forms, not procedures)
(define (ziku-and a b) (and a b))
(define (ziku-or a b) (or a b))

;; Not-equal operator (works for all types)
(define (ziku-ne a b) (not (equal? a b)))

;; Main program
(define (ziku-main halt)
  (let ((_alpha0 halt)) (let ((%p (list 'True))) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) (lambda (%v) (let ((%tag (car %v))) (cond ((eq? %tag 'True) (let ((%p 1)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha0) (_alpha0 %p)))) ((eq? %tag 'False) (let ((%p 0)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha0) (_alpha0 %p)))))))) ((lambda (%v) (let ((%tag (car %v))) (cond ((eq? %tag 'True) (let ((%p 1)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha0) (_alpha0 %p)))) ((eq? %tag 'False) (let ((%p 0)) (if (and (vector? %p) (eq? (vector-ref %p 0) 'ziku-thunk)) ((vector-ref %p 1) _alpha0) (_alpha0 %p))))))) %p)))))

;; Run with result printer
(ziku-main ziku-print-result)
